-- PitchAgent Pro: Supabase Database Setup Script
-- Run this in your Supabase SQL Editor (https://app.supabase.com/project/_/sql)

-- 1. Create 'profiles' table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  credits BIGINT DEFAULT 100,
  is_pro BOOLEAN DEFAULT FALSE,
  subscription_plan TEXT DEFAULT 'Free',
  context JSONB DEFAULT '[]',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create 'pitches' table for History
CREATE TABLE IF NOT EXISTS public.pitches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE,
  target_url TEXT NOT NULL,
  context TEXT,
  pitch_text TEXT,
  insights JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pitches ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for 'profiles'
CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = id);

-- 5. Create RLS Policies for 'pitches'
CREATE POLICY "Users can view own pitches" 
ON public.pitches FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own pitches" 
ON public.pitches FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 6. Trigger for updated_at (Optional but recommended)
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- [OPTIONAL] EMERGENCY FIX: Confirm all existing users
-- 만약 "Email not confirmed" 오류가 계속된다면 아래 주석을 풀고 실행하세요.
-- (주의: auth 스키마 접근 권한이 필요합니다)
-- UPDATE auth.users SET email_confirmed_at = NOW(), confirmed_at = NOW() WHERE email_confirmed_at IS NULL;
